# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.0
_src_path: gh:radio-aktywne/template-devcontainer
accountname: radio-aktywne
description: Devcontainer for CockroachDB databases 🪳
devcontainername: database-cockroach
docs: true
docsurl: https://radio-aktywne.github.io/devcontainer-database-cockroach
imagename: devcontainers/database-cockroach
registry: true
releases: true
reponame: devcontainer-database-cockroach
repourl: https://github.com/radio-aktywne/devcontainer-database-cockroach
